# fly.toml app configuration file generated for arek-ui-solid on 2024-01-05T23:00:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arek-ui-solid"
primary_region = "mad"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
